[functions.heartbeat]
verify_jwt = false

[functions.status]
verify_jwt = false

[functions.visit]
verify_jwt = false

[functions.temperature-history]
verify_jwt = false

[functions.disk-history]
verify_jwt = false

[functions.resource-history]
verify_jwt = false

[functions.smart-history]
verify_jwt = false
